(cl:in-package rf_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          AP_ID-VAL
          AP_ID
          TXMAC-VAL
          TXMAC
          CHAN-VAL
          CHAN
          N_SUB-VAL
          N_SUB
          N_ROWS-VAL
          N_ROWS
          N_COLS-VAL
          N_COLS
          BW-VAL
          BW
          MCS-VAL
          MCS
          RSSI-VAL
          RSSI
          FC-VAL
          FC
          SEQ_NUM-VAL
          SEQ_NUM
          CSI_REAL-VAL
          CSI_REAL
          CSI_IMAG-VAL
          CSI_IMAG
          RX_ID-VAL
          RX_ID
          MSG_ID-VAL
          MSG_ID
))