// Generated by gencpp from file csi_tools/SaveChannel.msg
// DO NOT EDIT!


#ifndef CSI_TOOLS_MESSAGE_SAVECHANNEL_H
#define CSI_TOOLS_MESSAGE_SAVECHANNEL_H

#include <ros/service_traits.h>


#include <csi_tools/SaveChannelRequest.h>
#include <csi_tools/SaveChannelResponse.h>


namespace csi_tools
{

struct SaveChannel
{

typedef SaveChannelRequest Request;
typedef SaveChannelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveChannel
} // namespace csi_tools


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::csi_tools::SaveChannel > {
  static const char* value()
  {
    return "e4f28584a2301cb8628c003709fe824c";
  }

  static const char* value(const ::csi_tools::SaveChannel&) { return value(); }
};

template<>
struct DataType< ::csi_tools::SaveChannel > {
  static const char* value()
  {
    return "csi_tools/SaveChannel";
  }

  static const char* value(const ::csi_tools::SaveChannel&) { return value(); }
};


// service_traits::MD5Sum< ::csi_tools::SaveChannelRequest> should match
// service_traits::MD5Sum< ::csi_tools::SaveChannel >
template<>
struct MD5Sum< ::csi_tools::SaveChannelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::csi_tools::SaveChannel >::value();
  }
  static const char* value(const ::csi_tools::SaveChannelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::csi_tools::SaveChannelRequest> should match
// service_traits::DataType< ::csi_tools::SaveChannel >
template<>
struct DataType< ::csi_tools::SaveChannelRequest>
{
  static const char* value()
  {
    return DataType< ::csi_tools::SaveChannel >::value();
  }
  static const char* value(const ::csi_tools::SaveChannelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::csi_tools::SaveChannelResponse> should match
// service_traits::MD5Sum< ::csi_tools::SaveChannel >
template<>
struct MD5Sum< ::csi_tools::SaveChannelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::csi_tools::SaveChannel >::value();
  }
  static const char* value(const ::csi_tools::SaveChannelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::csi_tools::SaveChannelResponse> should match
// service_traits::DataType< ::csi_tools::SaveChannel >
template<>
struct DataType< ::csi_tools::SaveChannelResponse>
{
  static const char* value()
  {
    return DataType< ::csi_tools::SaveChannel >::value();
  }
  static const char* value(const ::csi_tools::SaveChannelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CSI_TOOLS_MESSAGE_SAVECHANNEL_H
