// Generated by gencpp from file wiros_csi_node/ConfigureCSIResponse.msg
// DO NOT EDIT!


#ifndef WIROS_CSI_NODE_MESSAGE_CONFIGURECSIRESPONSE_H
#define WIROS_CSI_NODE_MESSAGE_CONFIGURECSIRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wiros_csi_node
{
template <class ContainerAllocator>
struct ConfigureCSIResponse_
{
  typedef ConfigureCSIResponse_<ContainerAllocator> Type;

  ConfigureCSIResponse_()
    : result()  {
    }
  ConfigureCSIResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::wiros_csi_node::ConfigureCSIResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wiros_csi_node::ConfigureCSIResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ConfigureCSIResponse_

typedef ::wiros_csi_node::ConfigureCSIResponse_<std::allocator<void> > ConfigureCSIResponse;

typedef boost::shared_ptr< ::wiros_csi_node::ConfigureCSIResponse > ConfigureCSIResponsePtr;
typedef boost::shared_ptr< ::wiros_csi_node::ConfigureCSIResponse const> ConfigureCSIResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wiros_csi_node::ConfigureCSIResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wiros_csi_node::ConfigureCSIResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::wiros_csi_node::ConfigureCSIResponse_<ContainerAllocator1> & lhs, const ::wiros_csi_node::ConfigureCSIResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::wiros_csi_node::ConfigureCSIResponse_<ContainerAllocator1> & lhs, const ::wiros_csi_node::ConfigureCSIResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace wiros_csi_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::wiros_csi_node::ConfigureCSIResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wiros_csi_node::ConfigureCSIResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wiros_csi_node::ConfigureCSIResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wiros_csi_node::ConfigureCSIResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wiros_csi_node::ConfigureCSIResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wiros_csi_node::ConfigureCSIResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wiros_csi_node::ConfigureCSIResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::wiros_csi_node::ConfigureCSIResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::wiros_csi_node::ConfigureCSIResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wiros_csi_node/ConfigureCSIResponse";
  }

  static const char* value(const ::wiros_csi_node::ConfigureCSIResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wiros_csi_node::ConfigureCSIResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n"
;
  }

  static const char* value(const ::wiros_csi_node::ConfigureCSIResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wiros_csi_node::ConfigureCSIResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConfigureCSIResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wiros_csi_node::ConfigureCSIResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wiros_csi_node::ConfigureCSIResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WIROS_CSI_NODE_MESSAGE_CONFIGURECSIRESPONSE_H
