// Generated by gencpp from file wiros_csi_node/ConfigureCSI.msg
// DO NOT EDIT!


#ifndef WIROS_CSI_NODE_MESSAGE_CONFIGURECSI_H
#define WIROS_CSI_NODE_MESSAGE_CONFIGURECSI_H

#include <ros/service_traits.h>


#include <wiros_csi_node/ConfigureCSIRequest.h>
#include <wiros_csi_node/ConfigureCSIResponse.h>


namespace wiros_csi_node
{

struct ConfigureCSI
{

typedef ConfigureCSIRequest Request;
typedef ConfigureCSIResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ConfigureCSI
} // namespace wiros_csi_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wiros_csi_node::ConfigureCSI > {
  static const char* value()
  {
    return "37e074cc5fb8a82d0a146e413ef0dc09";
  }

  static const char* value(const ::wiros_csi_node::ConfigureCSI&) { return value(); }
};

template<>
struct DataType< ::wiros_csi_node::ConfigureCSI > {
  static const char* value()
  {
    return "wiros_csi_node/ConfigureCSI";
  }

  static const char* value(const ::wiros_csi_node::ConfigureCSI&) { return value(); }
};


// service_traits::MD5Sum< ::wiros_csi_node::ConfigureCSIRequest> should match
// service_traits::MD5Sum< ::wiros_csi_node::ConfigureCSI >
template<>
struct MD5Sum< ::wiros_csi_node::ConfigureCSIRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wiros_csi_node::ConfigureCSI >::value();
  }
  static const char* value(const ::wiros_csi_node::ConfigureCSIRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wiros_csi_node::ConfigureCSIRequest> should match
// service_traits::DataType< ::wiros_csi_node::ConfigureCSI >
template<>
struct DataType< ::wiros_csi_node::ConfigureCSIRequest>
{
  static const char* value()
  {
    return DataType< ::wiros_csi_node::ConfigureCSI >::value();
  }
  static const char* value(const ::wiros_csi_node::ConfigureCSIRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wiros_csi_node::ConfigureCSIResponse> should match
// service_traits::MD5Sum< ::wiros_csi_node::ConfigureCSI >
template<>
struct MD5Sum< ::wiros_csi_node::ConfigureCSIResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wiros_csi_node::ConfigureCSI >::value();
  }
  static const char* value(const ::wiros_csi_node::ConfigureCSIResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wiros_csi_node::ConfigureCSIResponse> should match
// service_traits::DataType< ::wiros_csi_node::ConfigureCSI >
template<>
struct DataType< ::wiros_csi_node::ConfigureCSIResponse>
{
  static const char* value()
  {
    return DataType< ::wiros_csi_node::ConfigureCSI >::value();
  }
  static const char* value(const ::wiros_csi_node::ConfigureCSIResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WIROS_CSI_NODE_MESSAGE_CONFIGURECSI_H
