// Generated by gencpp from file rf_msgs/Station.msg
// DO NOT EDIT!


#ifndef RF_MSGS_MESSAGE_STATION_H
#define RF_MSGS_MESSAGE_STATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rf_msgs
{
template <class ContainerAllocator>
struct Station_
{
  typedef Station_<ContainerAllocator> Type;

  Station_()
    : header()
    , mac()
    , channel(0)
    , rssi(0)  {
      mac.assign(0);
  }
  Station_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , mac()
    , channel(0)
    , rssi(0)  {
  (void)_alloc;
      mac.assign(0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<uint8_t, 6>  _mac_type;
  _mac_type mac;

   typedef int32_t _channel_type;
  _channel_type channel;

   typedef int32_t _rssi_type;
  _rssi_type rssi;





  typedef boost::shared_ptr< ::rf_msgs::Station_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rf_msgs::Station_<ContainerAllocator> const> ConstPtr;

}; // struct Station_

typedef ::rf_msgs::Station_<std::allocator<void> > Station;

typedef boost::shared_ptr< ::rf_msgs::Station > StationPtr;
typedef boost::shared_ptr< ::rf_msgs::Station const> StationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rf_msgs::Station_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rf_msgs::Station_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rf_msgs::Station_<ContainerAllocator1> & lhs, const ::rf_msgs::Station_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.mac == rhs.mac &&
    lhs.channel == rhs.channel &&
    lhs.rssi == rhs.rssi;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rf_msgs::Station_<ContainerAllocator1> & lhs, const ::rf_msgs::Station_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rf_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rf_msgs::Station_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rf_msgs::Station_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rf_msgs::Station_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rf_msgs::Station_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rf_msgs::Station_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rf_msgs::Station_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rf_msgs::Station_<ContainerAllocator> >
{
  static const char* value()
  {
    return "10b6cc24ce2106ac7952f0affaba2507";
  }

  static const char* value(const ::rf_msgs::Station_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x10b6cc24ce2106acULL;
  static const uint64_t static_value2 = 0x7952f0affaba2507ULL;
};

template<class ContainerAllocator>
struct DataType< ::rf_msgs::Station_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rf_msgs/Station";
  }

  static const char* value(const ::rf_msgs::Station_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rf_msgs::Station_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#basic object which can be detected by wireless sensing.\n"
"\n"
"Header header\n"
"\n"
"#mac address\n"
"uint8[6] mac\n"
"\n"
"#wifi channel on which it is broadcast\n"
"int32 channel\n"
"\n"
"#measured rssi\n"
"int32 rssi\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::rf_msgs::Station_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rf_msgs::Station_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.mac);
      stream.next(m.channel);
      stream.next(m.rssi);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Station_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rf_msgs::Station_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rf_msgs::Station_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "mac[]" << std::endl;
    for (size_t i = 0; i < v.mac.size(); ++i)
    {
      s << indent << "  mac[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.mac[i]);
    }
    s << indent << "channel: ";
    Printer<int32_t>::stream(s, indent + "  ", v.channel);
    s << indent << "rssi: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rssi);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RF_MSGS_MESSAGE_STATION_H
